version: "3.5"

services:
  order_management_db:
    image: mysql:latest
    container_name: order_management_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=order_management_db
      - MYSQL_USER=order_management_user
      - MYSQL_PASSWORD=order_management_password
    ports:
      - "3306:3306"
    volumes:
      - .order_management-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
