spring:
  application:
    name: order-management
  config:
    import: "optional:configserver:http://localhost:48080"
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_management_db
    username: order_management_user
    password: order_management_password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
      generate-ddl: true
      show-sql: true
grpc:
  client:
    product_catalog:
      address: "static://127.0.0.1:6565"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
  server:
    port: 6566
