/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SubImport } from './routes/_sub'
import { Route as MainImport } from './routes/_main'
import { Route as AuthImport } from './routes/_auth'
import { Route as MainRestaurantsImport } from './routes/_main/restaurants'
import { Route as MainOrdersImport } from './routes/_main/orders'
import { Route as MainAccountImport } from './routes/_main/account'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as SubRestaurantSlugImport } from './routes/_sub/restaurant.$slug'

// Create/Update Routes

const SubRoute = SubImport.update({
  id: '/_sub',
  getParentRoute: () => rootRoute,
} as any)

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const MainRestaurantsRoute = MainRestaurantsImport.update({
  path: '/restaurants',
  getParentRoute: () => MainRoute,
} as any)

const MainOrdersRoute = MainOrdersImport.update({
  path: '/orders',
  getParentRoute: () => MainRoute,
} as any)

const MainAccountRoute = MainAccountImport.update({
  path: '/account',
  getParentRoute: () => MainRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const SubRestaurantSlugRoute = SubRestaurantSlugImport.update({
  path: '/restaurant/$slug',
  getParentRoute: () => SubRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_sub': {
      preLoaderRoute: typeof SubImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_main/account': {
      preLoaderRoute: typeof MainAccountImport
      parentRoute: typeof MainImport
    }
    '/_main/orders': {
      preLoaderRoute: typeof MainOrdersImport
      parentRoute: typeof MainImport
    }
    '/_main/restaurants': {
      preLoaderRoute: typeof MainRestaurantsImport
      parentRoute: typeof MainImport
    }
    '/_sub/restaurant/$slug': {
      preLoaderRoute: typeof SubRestaurantSlugImport
      parentRoute: typeof SubImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([AuthLoginRoute, AuthSignupRoute]),
  MainRoute.addChildren([
    MainAccountRoute,
    MainOrdersRoute,
    MainRestaurantsRoute,
  ]),
  SubRoute.addChildren([SubRestaurantSlugRoute]),
])

/* prettier-ignore-end */
