/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SubImport } from './routes/_sub'
import { Route as MainImport } from './routes/_main'
import { Route as MainRestaurantsImport } from './routes/_main/restaurants'
import { Route as MainOrdersImport } from './routes/_main/orders'
import { Route as MainAccountImport } from './routes/_main/account'
import { Route as SubRestaurantSlugImport } from './routes/_sub/restaurant.$slug'

// Create/Update Routes

const SubRoute = SubImport.update({
  id: '/_sub',
  getParentRoute: () => rootRoute,
} as any)

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const MainRestaurantsRoute = MainRestaurantsImport.update({
  path: '/restaurants',
  getParentRoute: () => MainRoute,
} as any)

const MainOrdersRoute = MainOrdersImport.update({
  path: '/orders',
  getParentRoute: () => MainRoute,
} as any)

const MainAccountRoute = MainAccountImport.update({
  path: '/account',
  getParentRoute: () => MainRoute,
} as any)

const SubRestaurantSlugRoute = SubRestaurantSlugImport.update({
  path: '/restaurant/$slug',
  getParentRoute: () => SubRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_sub': {
      preLoaderRoute: typeof SubImport
      parentRoute: typeof rootRoute
    }
    '/_main/account': {
      preLoaderRoute: typeof MainAccountImport
      parentRoute: typeof MainImport
    }
    '/_main/orders': {
      preLoaderRoute: typeof MainOrdersImport
      parentRoute: typeof MainImport
    }
    '/_main/restaurants': {
      preLoaderRoute: typeof MainRestaurantsImport
      parentRoute: typeof MainImport
    }
    '/_sub/restaurant/$slug': {
      preLoaderRoute: typeof SubRestaurantSlugImport
      parentRoute: typeof SubImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  MainRoute.addChildren([
    MainAccountRoute,
    MainOrdersRoute,
    MainRestaurantsRoute,
  ]),
  SubRoute.addChildren([SubRestaurantSlugRoute]),
])

/* prettier-ignore-end */
