server:
  port: 48081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:48761/eureka/

grpc:
  server:
    port: 38081
  client:
    order-management:
      address: "static://127.0.0.1:38089"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT
