server:
  port: 48086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  sql:
    init:
      mode: always
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/driver_availability_db?createDatabaseIfNotExist=true
    username: driver_availability_user
    password: driver_availability_password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create
    generate-ddl: true
    show-sql: true

grpc:
  server:
    port: 38086
