server:
  port: 48089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_management_db
    username: order_management_user
    password: order_management_password
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    generate-ddl: true
    show-sql: true
grpc:
  client:
    product_catalog:
      address: "static://127.0.0.1:6565"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
  server:
    port: 6566
