server:
  port: 48088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:48761/eureka/

spring:
  sql:
    init:
      mode: always
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/product_catalog_db?createDatabaseIfNotExist=true
    username: product_catalog_user
    password: product_catalog_password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create
    generate-ddl: true
    show-sql: true

grpc:
  server:
    port: 38088
