server:
  port: 48083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:48761/eureka/

# Eventually make api gateways only clients not server
grpc:
  server:
    port: 38083
  client:
    order-management:
      address: "static://127.0.0.1:38089"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
